#!/usr/bin/env bash
set -Eeuo pipefail
IFS=$'\n\t'

# Moodle Friendly Installation panel installer for Fedora/CentOS/RHEL/AlmaLinux/Rocky.
# This file is normally called by installation.sh.
# Usage: sudo bash installation-redhat.sh [repo-branch]

ENV_URL="https://raw.githubusercontent.com/moodle/moodle/main/public/admin/environment.xml"
INSTALL_DIR="${INSTALL_DIR:-/home/admin.moodle}"
NONINTERACTIVE="${NONINTERACTIVE:-0}"
PROGRESS_DIR="${PROGRESS_DIR:-/var/lib/moodle-friendly-installation}"
PROGRESS_FILE="${PROGRESS_FILE:-${PROGRESS_DIR}/installer-progress.env}"
REQUESTED_DB_ENGINE="${DB_ENGINE:-}"
REQUESTED_PANEL_DOMAIN="${PANEL_DOMAIN:-}"
REQUESTED_DB_ROOT_PASS="${DB_ROOT_PASS:-}"
REQUESTED_LE_EMAIL="${LE_EMAIL:-}"
TTY_IN_FD_OPENED=0

OS_ID=""
OS_VERSION_ID=""
OS_LIKE=""
OS_FAMILY=""
PKG_MANAGER=""
PHP_SERIES=""
PHP_BIN="/usr/bin/php"
PHP_FPM_SERVICE=""
PHP_FPM_SOCKET=""
DB_ENGINE="${DB_ENGINE:-}"
DB_SERVICE=""
DB_ROOT_PASS="${DB_ROOT_PASS:-}"
MOODLE_STABLE_BRANCH=""
PANEL_DOMAIN="${PANEL_DOMAIN:-}"
PUBLIC_IP=""
BASE_URL=""
SERVER_NAME=""
LE_EMAIL="${LE_EMAIL:-}"
MOODLE_VERSION=""
MOODLE_REQUIRES=""
PHP_REQUIRED=""
MARIADB_REQUIRED=""
MYSQL_REQUIRED=""

log() {
    printf '\n\n\n\033[1;32m==>\033[0m %s\n' "$*"
}

warn() {
    printf '\n\n\n\033[1;33mWARN:\033[0m %s\n' "$*" >&2
}

die() {
    printf '\n\n\n\033[1;31mERROR:\033[0m %s\n' "$*" >&2
    exit 1
}

need_root() {
    if [[ "${EUID}" -ne 0 ]]; then
        die "Run as root: sudo bash $0"
    fi
}

command_exists() {
    command -v "$1" >/dev/null 2>&1
}

version_ge() {
    # Returns true when $1 >= $2.
    [[ "$(printf '%s\n%s\n' "$2" "$1" | sort -V | head -n1)" == "$2" ]]
}

safe_php_string() {
    python3 - "$1" <<'PY'
import sys
s = sys.argv[1]
s = s.replace('\\', '\\\\').replace("'", "\\'")
print("'" + s + "'")
PY
}

ensure_progress_dir() {
    mkdir -p "${PROGRESS_DIR}"
    chmod 0700 "${PROGRESS_DIR}" 2>/dev/null || true
}

save_progress() {
    ensure_progress_dir

    local tmpfile="${PROGRESS_FILE}.tmp"
    {
        printf '# Generated by Moodle Friendly Installation installer.\n'
        printf '# This file allows the installer to resume safely after an interruption.\n'
        printf 'DB_ENGINE=%q\n' "${DB_ENGINE:-}"
        printf 'PANEL_DOMAIN=%q\n' "${PANEL_DOMAIN:-}"
        printf 'PANEL_DOMAIN_SELECTED=%q\n' "${PANEL_DOMAIN_SELECTED:-0}"
        printf 'DB_ROOT_PASS=%q\n' "${DB_ROOT_PASS:-}"
        printf 'PUBLIC_IP=%q\n' "${PUBLIC_IP:-}"
        printf 'BASE_URL=%q\n' "${BASE_URL:-}"
        printf 'SERVER_NAME=%q\n' "${SERVER_NAME:-}"
        printf 'LE_EMAIL=%q\n' "${LE_EMAIL:-}"
        printf 'MOODLE_VERSION=%q\n' "${MOODLE_VERSION:-}"
        printf 'MOODLE_REQUIRES=%q\n' "${MOODLE_REQUIRES:-}"
        printf 'MOODLE_STABLE_BRANCH=%q\n' "${MOODLE_STABLE_BRANCH:-}"
        printf 'PHP_REQUIRED=%q\n' "${PHP_REQUIRED:-}"
        printf 'PHP_SERIES=%q\n' "${PHP_SERIES:-}"
        printf 'PHP_BIN=%q\n' "${PHP_BIN:-}"
        printf 'PHP_FPM_SERVICE=%q\n' "${PHP_FPM_SERVICE:-}"
        printf 'PHP_FPM_SOCKET=%q\n' "${PHP_FPM_SOCKET:-}"
        printf 'MARIADB_REQUIRED=%q\n' "${MARIADB_REQUIRED:-}"
        printf 'MYSQL_REQUIRED=%q\n' "${MYSQL_REQUIRED:-}"
        printf 'DB_SERVICE=%q\n' "${DB_SERVICE:-}"
        printf 'STEP_BASE_PACKAGES=%q\n' "${STEP_BASE_PACKAGES:-0}"
        printf 'STEP_PHP=%q\n' "${STEP_PHP:-0}"
        printf 'STEP_DATABASE=%q\n' "${STEP_DATABASE:-0}"
        printf 'STEP_WEB_SERVERS=%q\n' "${STEP_WEB_SERVERS:-0}"
        printf 'STEP_CONFIG=%q\n' "${STEP_CONFIG:-0}"
        printf 'STEP_CRON=%q\n' "${STEP_CRON:-0}"
        printf 'STEP_LETS_ENCRYPT=%q\n' "${STEP_LETS_ENCRYPT:-0}"
        printf 'STEP_COMPLETE=%q\n' "${STEP_COMPLETE:-0}"
    } > "${tmpfile}"

    chmod 0600 "${tmpfile}" 2>/dev/null || true
    mv "${tmpfile}" "${PROGRESS_FILE}"
}

load_progress() {
    if [[ "${RESET_INSTALLER_PROGRESS:-0}" == "1" ]]; then
        rm -f "${PROGRESS_FILE}" 2>/dev/null || true
        return 0
    fi

    [[ -f "${PROGRESS_FILE}" ]] || return 0

    # shellcheck source=/dev/null
    source "${PROGRESS_FILE}"

    # Explicit environment variables win over saved progress.
    [[ -n "${REQUESTED_DB_ENGINE:-}" ]] && DB_ENGINE="${REQUESTED_DB_ENGINE}"
    [[ -n "${REQUESTED_PANEL_DOMAIN:-}" ]] && PANEL_DOMAIN="${REQUESTED_PANEL_DOMAIN}"
    [[ -n "${REQUESTED_DB_ROOT_PASS:-}" ]] && DB_ROOT_PASS="${REQUESTED_DB_ROOT_PASS}"
    [[ -n "${REQUESTED_LE_EMAIL:-}" ]] && LE_EMAIL="${REQUESTED_LE_EMAIL}"

    log "Loaded installer progress from ${PROGRESS_FILE}"
}

mark_progress_done() {
    local var_name="$1"
    printf -v "${var_name}" '%s' "1"
    save_progress
}

open_interactive_terminal() {
    if [[ "${NONINTERACTIVE}" == "1" ]]; then
        return 0
    fi

    if [[ ! -e /dev/tty ]]; then
        die "Interactive installation requires a TTY. Run from SSH/terminal, or use NONINTERACTIVE=1 with DB_ENGINE and PANEL_DOMAIN."
    fi

    # Keep a stable terminal handle. This avoids prompts disappearing or read blocking
    # when the installer itself was started through curl | sudo bash.
    exec 3</dev/tty || die "Could not open /dev/tty for reading."
    exec 4>/dev/tty || die "Could not open /dev/tty for writing."
    TTY_IN_FD_OPENED=1
}

configure_selinux_permissive() {
    local state=""
    local selinux_active="0"

    if command_exists getenforce; then
        state="$(getenforce 2>/dev/null || true)"
        if [[ "${state}" == "Enforcing" || "${state}" == "Permissive" ]]; then
            selinux_active="1"
        fi
    elif [[ -f /etc/selinux/config ]] && grep -qiE '^[[:space:]]*SELINUX=(enforcing|permissive)[[:space:]]*$' /etc/selinux/config; then
        selinux_active="1"
    fi

    [[ "${selinux_active}" == "1" ]] || return 0

    if [[ "${state}" == "Enforcing" ]]; then
        log "SELinux is active in enforcing mode. Switching the current session to permissive."
        setenforce 0 || warn "Could not execute setenforce 0. Continuing, but SELinux may still block services."
    else
        log "SELinux is active. Ensuring permanent mode is permissive."
    fi

    if [[ -f /etc/selinux/config ]]; then
        if grep -qE '^[[:space:]]*SELINUX=' /etc/selinux/config; then
            sed -i -E 's/^[[:space:]]*SELINUX=.*/SELINUX=permissive/' /etc/selinux/config || warn "Could not update /etc/selinux/config."
        else
            printf '\nSELINUX=permissive\n' >> /etc/selinux/config || warn "Could not append SELINUX=permissive to /etc/selinux/config."
        fi
    else
        warn "/etc/selinux/config was not found. Runtime SELinux mode was handled only for the current boot."
    fi
}

prompt_text() {
    local var_name="$1"
    local label="$2"
    local default_value="${3:-}"
    local value=""

    if [[ "${NONINTERACTIVE}" == "1" ]]; then
        value="${!var_name:-${default_value}}"
    else
        [[ "${TTY_IN_FD_OPENED}" == "1" ]] || open_interactive_terminal

        if [[ -n "${default_value}" ]]; then
            printf '%s [%s]: ' "${label}" "${default_value}" >&4
            if ! IFS= read -r value <&3; then
                die "Could not read input from the terminal."
            fi
            value="${value:-${default_value}}"
        else
            printf '%s: ' "${label}" >&4
            if ! IFS= read -r value <&3; then
                die "Could not read input from the terminal."
            fi
        fi
    fi

    printf -v "${var_name}" '%s' "${value}"
}

prompt_secret() {
    local var_name="$1"
    local label="$2"
    local value=""

    if [[ "${NONINTERACTIVE}" == "1" ]]; then
        value="${!var_name:-}"
        [[ -n "${value}" ]] || die "Variable ${var_name} must be defined when NONINTERACTIVE=1."
    else
        [[ "${TTY_IN_FD_OPENED}" == "1" ]] || open_interactive_terminal
        printf '%s: ' "${label}" >&4
        if ! IFS= read -r -s value <&3; then
            printf '
' >&4
            die "Could not read password from the terminal."
        fi
        printf '
' >&4
    fi

    printf -v "${var_name}" '%s' "${value}"
}

ui_available() {
    [[ "${NONINTERACTIVE}" != "1" ]] && [[ -e /dev/tty ]] && command_exists whiptail
}

prompt_database_select() {
    if [[ -n "${DB_ENGINE:-}" ]]; then
        DB_ENGINE="$(printf '%s' "${DB_ENGINE}" | tr '[:upper:]' '[:lower:]')"
        case "${DB_ENGINE}" in
            mariadb|mysql)
                log "Using saved database option: ${DB_ENGINE}"
                save_progress
                return 0
                ;;
            *)
                die "Invalid saved database option: ${DB_ENGINE}. Use mariadb or mysql."
                ;;
        esac
    fi

    if [[ "${NONINTERACTIVE}" == "1" ]]; then
        DB_ENGINE="${DB_ENGINE:-mariadb}"
        DB_ENGINE="$(printf '%s' "${DB_ENGINE}" | tr '[:upper:]' '[:lower:]')"
    elif ui_available; then
        local choice=""
        choice="$(whiptail             --title "Moodle Friendly Installation"             --menu "Database to install"             14 78 2             "mysql" "MySQL ${MYSQL_REQUIRED:+>= ${MYSQL_REQUIRED}}"             "mariadb" "MariaDB ${MARIADB_REQUIRED:+>= ${MARIADB_REQUIRED}}"             3>&1 1>&2 2>&3 < /dev/tty)" || die "Database selection cancelled."
        DB_ENGINE="${choice}"
    else
        [[ "${TTY_IN_FD_OPENED}" == "1" ]] || open_interactive_terminal
        local options=("mariadb" "mysql")
        local choice=""
        printf '
Database to install:
' >&4
        PS3="Select an option [1-2]: "
        select choice in "${options[@]}"; do
            case "${choice}" in
                mariadb|mysql)
                    DB_ENGINE="${choice}"
                    break
                    ;;
                *)
                    printf 'Invalid option. Select 1 or 2.
' >&4
                    ;;
            esac
        done <&3 >&4 2>&4
    fi

    case "${DB_ENGINE}" in
        mariadb|mysql) ;;
        *) die "Invalid database option: ${DB_ENGINE}. Use mariadb or mysql." ;;
    esac

    save_progress
}

prompt_domain_box() {
    if [[ "${PANEL_DOMAIN_SELECTED:-0}" == "1" && "${NONINTERACTIVE}" != "1" ]]; then
        if [[ -n "${PANEL_DOMAIN:-}" ]]; then
            log "Using saved panel access option: ${PANEL_DOMAIN}"
        else
            log "Using saved panel access option: public IP"
        fi
        return 0
    fi

    if [[ "${NONINTERACTIVE}" == "1" ]]; then
        PANEL_DOMAIN="${PANEL_DOMAIN:-}"
    elif ui_available; then
        local value=""
        value="$(whiptail             --title "Moodle Friendly Installation"             --inputbox "Panel domain, or leave blank to use the public IP."             10 78 "${PANEL_DOMAIN:-}"             3>&1 1>&2 2>&3 < /dev/tty)" || die "Domain input cancelled."
        PANEL_DOMAIN="${value}"
    else
        prompt_text PANEL_DOMAIN "Panel domain, or press ENTER to use the public IP" ""
    fi

    PANEL_DOMAIN="$(printf '%s' "${PANEL_DOMAIN}" | tr '[:upper:]' '[:lower:]' | sed -E 's#^https?://##; s#/.*$##; s/:.*$//')"
    PANEL_DOMAIN_SELECTED=1
    save_progress
}

generate_strong_password() {
    python3 - <<'GENPASS'
import random
import secrets

lower = "abcdefghijkmnopqrstuvwxyz"
upper = "ABCDEFGHJKLMNPQRSTUVWXYZ"
digits = "23456789"
symbols = "@#%_-+="
alphabet = lower + upper + digits + symbols
password = [
    secrets.choice(lower),
    secrets.choice(upper),
    secrets.choice(digits),
    secrets.choice(symbols),
]
password.extend(secrets.choice(alphabet) for _ in range(28))
random.SystemRandom().shuffle(password)
print("".join(password))
GENPASS
}

detect_os() {
    [[ -r /etc/os-release ]] || die "Could not detect the Linux distribution."
    # shellcheck source=/dev/null
    source /etc/os-release
    OS_ID="${ID:-}"
    OS_VERSION_ID="${VERSION_ID:-}"
    OS_LIKE="${ID_LIKE:-}"

    case "${OS_ID} ${OS_LIKE}" in
        *fedora*)
            OS_FAMILY="fedora"
            PKG_MANAGER="dnf"
            ;;
        *centos*|*rhel*|*rocky*|*almalinux*)
            OS_FAMILY="rhel"
            if command_exists dnf; then
                PKG_MANAGER="dnf"
            elif command_exists yum; then
                PKG_MANAGER="yum"
            else
                die "RHEL-family system detected, but neither dnf nor yum is available."
            fi
            ;;
        *)
            die "This installer supports Fedora/CentOS/RHEL/AlmaLinux/Rocky only. Detected: ID=${OS_ID}, ID_LIKE=${OS_LIKE}. Use install/installation.sh to auto-select the correct installer."
            ;;
    esac
    log "Detected system: ${OS_ID} ${OS_VERSION_ID} (${OS_FAMILY})"
}

pkg_retry() {
    local output
    local code
    local tries="${PKG_LOCK_RETRIES:-60}"
    local delay="${PKG_LOCK_SLEEP:-5}"
    local i

    for ((i = 1; i <= tries; i++)); do
        output="$("$@" 2>&1)"
        code=$?

        if [[ -n "${output}" ]]; then
            printf '%s\n' "${output}"
        fi

        if [[ "${code}" -eq 0 ]]; then
            return 0
        fi

        if grep -qiE 'Failed to obtain rpm transaction lock|Another transaction is in progress|transaction lock|rpm.*lock|dnf.*lock|yum.*lock' <<< "${output}"; then
            warn "Package manager lock is busy. Retry ${i}/${tries} in ${delay}s..."
            sleep "${delay}"
            continue
        fi

        return "${code}"
    done

    warn "Package manager lock did not become available after ${tries} attempts."
    return 1
}

pkg_update() {
    pkg_retry "${PKG_MANAGER}" makecache -y || true
}

pkg_install() {
    pkg_retry "${PKG_MANAGER}" install -y "$@"
}


install_nodejs_22() {
    log "Installing Node.js 22"

    if command_exists node && node -v 2>/dev/null | grep -qE '^v22\.'; then
        command_exists npm || die "npm was not found with the current Node.js 22 installation."
        command_exists npx || die "npx was not found with the current Node.js 22 installation."
        return 0
    fi

    if [[ "${PKG_MANAGER}" == "dnf" ]]; then
        ${PKG_MANAGER} -y module reset nodejs >/dev/null 2>&1 || true
    fi

    curl -fsSL https://rpm.nodesource.com/setup_22.x -o /tmp/nodesource_setup_22.sh || die "Failed to download NodeSource setup for Node.js 22."
    bash /tmp/nodesource_setup_22.sh || die "Failed to configure NodeSource repository for Node.js 22."
    rm -f /tmp/nodesource_setup_22.sh

    pkg_install nodejs

    command_exists node || die "Node.js was not found after installation."
    command_exists npm || die "npm was not found after Node.js installation."
    command_exists npx || die "npx was not found after Node.js installation."

    if ! node -v 2>/dev/null | grep -qE '^v22\.'; then
        die "Node.js 22 was expected, but detected $(node -v 2>/dev/null || printf 'unknown')."
    fi
}

install_gradle_8_14_2() {
    local gradle_version="8.14.2"
    local gradle_home="/opt/gradle/gradle-${gradle_version}"
    local gradle_zip="/tmp/gradle-${gradle_version}-bin.zip"
    local gradle_url="${GRADLE_URL:-https://services.gradle.org/distributions/gradle-${gradle_version}-bin.zip}"

    log "Installing Gradle ${gradle_version}"

    if command_exists gradle && gradle --version 2>/dev/null | grep -q "Gradle ${gradle_version}"; then
        return 0
    fi

    mkdir -p /opt/gradle
    if [[ ! -x "${gradle_home}/bin/gradle" ]]; then
        curl -fsSL "${gradle_url}" -o "${gradle_zip}" || die "Failed to download Gradle ${gradle_version}."
        rm -rf "${gradle_home}"
        unzip -q "${gradle_zip}" -d /opt/gradle || die "Failed to extract Gradle ${gradle_version}."
        rm -f "${gradle_zip}"
    fi

    ln -sfn "${gradle_home}/bin/gradle" /usr/local/bin/gradle

    cat > /etc/profile.d/gradle.sh <<EOF
export GRADLE_HOME="${gradle_home}"
export PATH="\${GRADLE_HOME}/bin:\${PATH}"
EOF
    chmod 0644 /etc/profile.d/gradle.sh

    export GRADLE_HOME="${gradle_home}"
    export PATH="${GRADLE_HOME}/bin:${PATH}"

    command_exists gradle || die "Gradle command was not found after installation."
}

configure_java_home() {
    local javac_path=""
    local java_home=""

    command_exists javac || die "OpenJDK 17 was not installed correctly because javac was not found."

    javac_path="$(readlink -f "$(command -v javac)")"
    java_home="$(dirname "$(dirname "${javac_path}")")"

    cat > /etc/profile.d/java-17.sh <<EOF
export JAVA_HOME="${java_home}"
export PATH="\${JAVA_HOME}/bin:\${PATH}"
EOF
    chmod 0644 /etc/profile.d/java-17.sh

    export JAVA_HOME="${java_home}"
    export PATH="${JAVA_HOME}/bin:${PATH}"

    java -version >/dev/null 2>&1 || die "Java was not found after setting JAVA_HOME."
}

ensure_imagemagick_magick_command() {
    log "Checking ImageMagick magick command"

    if command_exists magick; then
        return 0
    fi

    if ! command_exists convert; then
        die "ImageMagick was installed, but neither magick nor convert was found."
    fi

    # ImageMagick 6 exposes convert/identify/mogrify instead of the ImageMagick 7 magick entrypoint.
    # This wrapper keeps Cordova/icon scripts compatible on distributions that still package ImageMagick 6.
    cat > /usr/local/bin/magick <<'EOF'
#!/usr/bin/env bash
set -Eeuo pipefail

subcommand="${1:-}"
case "${subcommand}" in
    identify|convert|mogrify|montage|composite|compare|conjure|display|animate|stream|import)
        if command -v "${subcommand}" >/dev/null 2>&1; then
            exec "$@"
        fi
        ;;
esac

exec convert "$@"
EOF
    chmod 0755 /usr/local/bin/magick
}

accept_android_sdk_licenses() {
    local sdkmanager="$1"
    local code=0

    set +o pipefail
    yes | "${sdkmanager}" --licenses >/dev/null
    code=$?
    set -o pipefail

    return "${code}"
}

install_android_sdk_packages() {
    local sdkmanager="$1"
    local sdk_root="$2"
    shift 2
    local code=0

    set +o pipefail
    yes | "${sdkmanager}" --sdk_root="${sdk_root}" --install "$@"
    code=$?
    set -o pipefail

    return "${code}"
}

install_android_sdk() {
    local android_sdk_root="${ANDROID_SDK_ROOT:-/opt/android-sdk}"
    local cmdline_tools_url="${ANDROID_CMDLINE_TOOLS_URL:-https://dl.google.com/android/repository/commandlinetools-linux-14742923_latest.zip}"
    local cmdline_tools_sha256="${ANDROID_CMDLINE_TOOLS_SHA256:-48833c34b761c10cb20bcd16582129395d121b27a99568fbffa64d887684f38f833}"
    local cmdline_tools_zip="/tmp/android-commandlinetools.zip"
    local sdkmanager="${android_sdk_root}/cmdline-tools/latest/bin/sdkmanager"

    log "Installing Android SDK command-line tools and build packages"

    mkdir -p "${android_sdk_root}/cmdline-tools"

    if [[ ! -x "${sdkmanager}" ]]; then
        curl -fsSL "${cmdline_tools_url}" -o "${cmdline_tools_zip}" || die "Failed to download Android SDK command-line tools."

        rm -rf "${android_sdk_root}/cmdline-tools/latest" "${android_sdk_root}/cmdline-tools/cmdline-tools"
        unzip -q "${cmdline_tools_zip}" -d "${android_sdk_root}/cmdline-tools" || die "Failed to extract Android SDK command-line tools."
        mv "${android_sdk_root}/cmdline-tools/cmdline-tools" "${android_sdk_root}/cmdline-tools/latest"
        rm -f "${cmdline_tools_zip}"
    fi

    chown -R root:root "${android_sdk_root}"

    cat > /etc/profile.d/android-sdk.sh <<EOF
export ANDROID_HOME="${android_sdk_root}"
export ANDROID_SDK_ROOT="${android_sdk_root}"
export PATH="\${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin:\${ANDROID_SDK_ROOT}/platform-tools:\${ANDROID_SDK_ROOT}/build-tools/36.0.0:\${PATH}"
EOF
    chmod 0644 /etc/profile.d/android-sdk.sh

    export ANDROID_HOME="${android_sdk_root}"
    export ANDROID_SDK_ROOT="${android_sdk_root}"
    export PATH="${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin:${ANDROID_SDK_ROOT}/platform-tools:${ANDROID_SDK_ROOT}/build-tools/36.0.0:${PATH}"

    [[ -x "${sdkmanager}" ]] || die "sdkmanager was not found after Android SDK command-line tools installation."

    accept_android_sdk_licenses "${sdkmanager}" || warn "Could not pre-accept all Android SDK licenses before package installation. Continuing with package installation."
    install_android_sdk_packages "${sdkmanager}" "${ANDROID_SDK_ROOT}" \
        "platform-tools" \
        "platforms;android-36" \
        "build-tools;36.0.0" || die "Failed to install Android SDK platform 36 and build-tools 36.0.0."
    accept_android_sdk_licenses "${sdkmanager}" || warn "Could not accept all Android SDK licenses after package installation."

    [[ -d "${ANDROID_SDK_ROOT}/platforms/android-36" ]] || die "Android platform android-36 was not installed."
    [[ -d "${ANDROID_SDK_ROOT}/build-tools/36.0.0" ]] || die "Android build-tools 36.0.0 was not installed."
}

install_base_packages() {
    dnf install -y adoptium-temurin-java-repository
    dnf config-manager setopt adoptium-temurin-java-repository.enabled=1 -y
    dnf clean all -y
    dnf makecache --refresh -y
    local base_packages=(
        ca-certificates curl wget gnupg2 unzip zip tar git bind-utils cronie openssl python3 sed grep gawk coreutils newt
        make gcc gcc-c++ temurin-17-jdk ImageMagick
    )

    log "Installing base packages"
    pkg_update
    pkg_install "${base_packages[@]}" policycoreutils-python-utils || pkg_install "${base_packages[@]}"
    systemctl enable --now crond >/dev/null 2>&1 || true

    configure_java_home
    install_nodejs_22
    install_gradle_8_14_2
    ensure_imagemagick_magick_command
    install_android_sdk
}

fetch_moodle_environment() {
    local tmpxml="/tmp/moodle-environment.xml"
    local outenv="/tmp/moodle-env-requirements.env"

    log "Reading current Moodle requirements from environment.xml"
    curl -fsSL "${ENV_URL}" -o "${tmpxml}" || die "Failed to download ${ENV_URL}"

    python3 - "${tmpxml}" > "${outenv}" <<'PY'
import shlex
import sys
import xml.etree.ElementTree as ET

xml_path = sys.argv[1]
root = ET.parse(xml_path).getroot()
moodles = list(root.iter('MOODLE'))
if not moodles:
    raise SystemExit('Nenhum bloco MOODLE encontrado no environment.xml')

moodle = moodles[-1]

def emit(key, value):
    print(f'{key}={shlex.quote(value or "")}')

php_required = ''
for item in moodle.iter('PHP'):
    if item.attrib.get('level') == 'required':
        php_required = item.attrib.get('version', '').strip()

vendors = {}
for vendor in moodle.iter('VENDOR'):
    name = vendor.attrib.get('name', '').strip().lower()
    if name in {'mariadb', 'mysql'}:
        vendors[name] = vendor.attrib.get('version', '').strip()

emit('MOODLE_VERSION', moodle.attrib.get('version', '').strip())
emit('MOODLE_REQUIRES', moodle.attrib.get('requires', '').strip())
emit('PHP_REQUIRED', php_required)
emit('MARIADB_REQUIRED', vendors.get('mariadb', ''))
emit('MYSQL_REQUIRED', vendors.get('mysql', ''))
PY

    # shellcheck source=/tmp/moodle-env-requirements.env
    source "${outenv}"

    [[ -n "${MOODLE_VERSION}" ]] || die "Could not detect the Moodle version."
    [[ -n "${PHP_REQUIRED}" ]] || die "Could not detect the required PHP version."
    [[ -n "${MARIADB_REQUIRED}" ]] || warn "Could not detect the required MariaDB version in XML."
    [[ -n "${MYSQL_REQUIRED}" ]] || warn "Could not detect the required MySQL version in XML."

    PHP_SERIES="$(printf '%s' "${PHP_REQUIRED}" | awk -F. '{print $1"."$2}')"
    local moodle_major moodle_minor
    moodle_major="${MOODLE_VERSION%%.*}"
    moodle_minor="${MOODLE_VERSION#*.}"
    moodle_minor="${moodle_minor%%.*}"
    if [[ "${moodle_major}" =~ ^[0-9]+$ ]] && [[ "${moodle_minor}" =~ ^[0-9]+$ ]]; then
        MOODLE_STABLE_BRANCH="$(printf 'MOODLE_%d%02d_STABLE' "${moodle_major}" "${moodle_minor}")"
    else
        MOODLE_STABLE_BRANCH="MOODLE_${MOODLE_VERSION/./}_STABLE"
    fi
    log "Moodle ${MOODLE_VERSION} requires PHP >= ${PHP_REQUIRED}, MariaDB >= ${MARIADB_REQUIRED:-?}, MySQL >= ${MYSQL_REQUIRED:-?}"
    save_progress
}

ask_install_options() {
    log "Starting interactive installer questions"

    prompt_database_select
    prompt_domain_box

    local generated_db_root_pass="0"
    if [[ -n "${DB_ROOT_PASS:-}" ]]; then
        log "Using saved/existing database root password."
    else
        DB_ROOT_PASS="$(generate_strong_password)"
        generated_db_root_pass="1"
        save_progress
    fi

    if [[ "${generated_db_root_pass}" == "1" ]]; then
        [[ ${#DB_ROOT_PASS} -ge 16 ]] || die "The generated database root password is unexpectedly short."
        [[ "${DB_ROOT_PASS}" =~ [[:upper:]] ]] || die "The generated database root password must contain at least one uppercase letter."
        [[ "${DB_ROOT_PASS}" =~ [[:lower:]] ]] || die "The generated database root password must contain at least one lowercase letter."
        [[ "${DB_ROOT_PASS}" =~ [[:digit:]] ]] || die "The generated database root password must contain at least one number."
        [[ "${DB_ROOT_PASS}" =~ [^[:alnum:]] ]] || die "The generated database root password must contain at least one special character."
    fi

    save_progress
}

is_valid_panel_domain() {
    local domain="$1"

    [[ -n "${domain}" ]] || return 1
    [[ ${#domain} -le 253 ]] || return 1
    [[ "${domain}" != *".."* ]] || return 1
    [[ "${domain}" =~ ^([a-z0-9]([a-z0-9-]{0,61}[a-z0-9])?\.)+[a-z]{2,63}$ ]]
}

resolve_domain_a_records() {
    local domain="$1"
    local output=""

    if command_exists dig; then
        output="$(dig +time=2 +tries=1 +short A "${domain}" 2>/dev/null || true)"
    elif command_exists host; then
        output="$(host -t A "${domain}" 2>/dev/null | sed -n 's/^.* has address //p' || true)"
    elif command_exists getent; then
        output="$(getent ahostsv4 "${domain}" 2>/dev/null | sed -n 's/^\([0-9][0-9.]*\).*$/\1/p' || true)"
    fi

    printf '%s\n' "${output}" \
        | sed -n '/^[0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*$/p' \
        | sort -u \
        | tr '\n' ' ' \
        | sed 's/[[:space:]]*$//'
}

first_ipv4_from_text() {
    local text="$*"

    printf '%s\n' "${text}" \
        | grep -Eo '([0-9]{1,3}\.){3}[0-9]{1,3}' \
        | sed -n '1p' \
        || true

    return 0
}

detect_public_ip() {
    local detected=""

    detected="$(curl -fsSL --max-time 8 https://api.ipify.org 2>/dev/null || true)"
    PUBLIC_IP="$(first_ipv4_from_text "${detected}")"

    if [[ -z "${PUBLIC_IP}" ]]; then
        detected="$(curl -fsSL --max-time 8 https://ifconfig.me/ip 2>/dev/null || true)"
        PUBLIC_IP="$(first_ipv4_from_text "${detected}")"
    fi

    if [[ -z "${PUBLIC_IP}" ]]; then
        detected="$(hostname -I 2>/dev/null || true)"
        PUBLIC_IP="$(first_ipv4_from_text "${detected}")"
    fi

    [[ -n "${PUBLIC_IP}" ]] || die "Could not detect an IPv4 address for this server."
    log "Detected public IP: ${PUBLIC_IP}"
    save_progress
}

check_dns_before_continue() {
    while true; do
        if [[ -z "${PANEL_DOMAIN}" ]]; then
            SERVER_NAME="_"
            BASE_URL="http://${PUBLIC_IP}"
            log "The panel installation will be available by IP: ${BASE_URL}"
            save_progress
            return
        fi

        if ! is_valid_panel_domain "${PANEL_DOMAIN}"; then
            if [[ "${NONINTERACTIVE}" == "1" ]]; then
                die "Invalid domain: ${PANEL_DOMAIN}. Use only a valid domain, without http://, without path and without spaces."
            fi

            warn "Invalid domain: ${PANEL_DOMAIN}."
            printf '
Invalid domain: %s.
' "${PANEL_DOMAIN}" >&4
            printf 'Use only a valid domain, without http://, without path and without spaces.
' >&4
            printf 'Example: panel.example.com, or leave blank to use the public IP.
' >&4
            printf 'Press ENTER to type the domain again...' >&4
            if ! IFS= read -r _ <&3; then
                die "Could not read input from the terminal."
            fi
            printf '
' >&4
            PANEL_DOMAIN=""
            PANEL_DOMAIN_SELECTED=0
            save_progress
            prompt_domain_box
            continue
        fi

        local resolved=""
        resolved="$(resolve_domain_a_records "${PANEL_DOMAIN}")"
        if [[ -z "${resolved}" ]]; then
            if [[ "${NONINTERACTIVE}" == "1" ]]; then
                die "The domain ${PANEL_DOMAIN} does not have a published A record yet. Point DNS to ${PUBLIC_IP} and run this installer again."
            fi

            warn "The domain ${PANEL_DOMAIN} does not have a published A record yet."
            printf '
The domain %s does not have a published A record yet.
' "${PANEL_DOMAIN}" >&4
            printf 'Point DNS to %s, or type another domain.
' "${PUBLIC_IP}" >&4
            printf 'Press ENTER to type the domain again...' >&4
            if ! IFS= read -r _ <&3; then
                die "Could not read input from the terminal."
            fi
            printf '
' >&4
            PANEL_DOMAIN=""
            PANEL_DOMAIN_SELECTED=0
            save_progress
            prompt_domain_box
            continue
        fi

        if ! printf ' %s ' "${resolved}" | grep -q " ${PUBLIC_IP} "; then
            if [[ "${NONINTERACTIVE}" == "1" ]]; then
                die "DNS mismatch for ${PANEL_DOMAIN}. Resolved: ${resolved}. Expected: ${PUBLIC_IP}. Fix DNS and run this installer again."
            fi

            warn "DNS mismatch for ${PANEL_DOMAIN}. Resolved: ${resolved}. Expected: ${PUBLIC_IP}."
            printf '
DNS mismatch for %s.
' "${PANEL_DOMAIN}" >&4
            printf 'Resolved: %s
' "${resolved}" >&4
            printf 'Expected: %s
' "${PUBLIC_IP}" >&4
            printf 'Fix DNS, or type another domain.
' >&4
            printf 'Press ENTER to type the domain again...' >&4
            if ! IFS= read -r _ <&3; then
                die "Could not read input from the terminal."
            fi
            printf '
' >&4
            PANEL_DOMAIN=""
            PANEL_DOMAIN_SELECTED=0
            save_progress
            prompt_domain_box
            continue
        fi

        SERVER_NAME="${PANEL_DOMAIN}"
        BASE_URL="https://${PANEL_DOMAIN}"
        log "DNS verified: ${PANEL_DOMAIN} points to ${PUBLIC_IP}"
        save_progress
        return
    done
}

install_php() {
    log "Installing PHP ${PHP_SERIES} and extensions used by Moodle/the panel"

    if [[ "${OS_FAMILY}" == "rhel" ]]; then
        local major="${OS_VERSION_ID%%.*}"
        if [[ "${major}" =~ ^[0-9]+$ ]] && [[ "${major}" -lt 8 ]]; then
            die "CentOS/RHEL ${OS_VERSION_ID} is not supported for modern PHP. Use CentOS Stream/RHEL/Alma/Rocky 8+ or Fedora."
        fi

        pkg_install epel-release || true
        if ! rpm -q remi-release >/dev/null 2>&1; then
            rpm -Uvh "https://rpms.remirepo.net/enterprise/remi-release-${major}.rpm" || warn "Could not install remi-release automatically. Trying the default repository."
        fi
        ${PKG_MANAGER} module reset -y php || true
        ${PKG_MANAGER} module enable -y "php:remi-${PHP_SERIES}" || warn "Could not enable php:remi-${PHP_SERIES}; trying the default package."
    fi

    pkg_install php php-cli php-fpm php-mysqlnd php-curl php-xml php-mbstring php-zip php-gd php-intl php-soap php-opcache php-bcmath php-ldap
    PHP_BIN="/usr/bin/php"
    PHP_FPM_SERVICE="php-fpm"
    PHP_FPM_SOCKET="/run/php-fpm/www.sock"

    command_exists "${PHP_BIN}" || die "PHP was not found at ${PHP_BIN}."
    local php_current=""
    php_current="$(${PHP_BIN} -r 'echo PHP_VERSION;' 2>/dev/null || true)"
    [[ -n "${php_current}" ]] || die "Could not read the installed PHP version."
    version_ge "${php_current}" "${PHP_REQUIRED}" || die "Installed PHP (${php_current}) is lower than the Moodle requirement (${PHP_REQUIRED})."

    tune_php_ini
    systemctl enable --now "${PHP_FPM_SERVICE}"
    systemctl restart "${PHP_FPM_SERVICE}"
    log "PHP ativo: ${php_current} (${PHP_FPM_SERVICE})"
}

tune_php_ini() {
    local files=("/etc/php.ini")
    if [[ -f /etc/php-fpm.d/www.conf ]]; then
        sed -i "s/^user = .*/user = apache/" /etc/php-fpm.d/www.conf || true
        sed -i "s/^group = .*/group = apache/" /etc/php-fpm.d/www.conf || true
        sed -i "s#^listen = .*#listen = ${PHP_FPM_SOCKET}#" /etc/php-fpm.d/www.conf || true
        sed -i "s/^;\?listen.owner = .*/listen.owner = apache/" /etc/php-fpm.d/www.conf || true
        sed -i "s/^;\?listen.group = .*/listen.group = apache/" /etc/php-fpm.d/www.conf || true
        sed -i "s/^;\?listen.mode = .*/listen.mode = 0660/" /etc/php-fpm.d/www.conf || true
    fi

    for file in "${files[@]}"; do
        [[ -f "${file}" ]] || continue
        sed -i \
            -e 's/^memory_limit = .*/memory_limit = 512M/' \
            -e 's/^max_execution_time = .*/max_execution_time = 300/' \
            -e 's/^post_max_size = .*/post_max_size = 128M/' \
            -e 's/^upload_max_filesize = .*/upload_max_filesize = 128M/' \
            -e 's/^max_input_vars = .*/max_input_vars = 5000/' \
            -e 's/^;max_input_vars = .*/max_input_vars = 5000/' \
            -e 's/^date.timezone = .*/date.timezone = America\/Sao_Paulo/' \
            -e 's/^;date.timezone =.*/date.timezone = America\/Sao_Paulo/' \
            "${file}" || true
    done
}

install_database() {
    if [[ "${DB_ENGINE}" == "mariadb" ]]; then
        install_mariadb
    else
        install_mysql
    fi
    configure_database_root
    validate_database_version
}

install_mariadb() {
    log "Installing MariaDB >= ${MARIADB_REQUIRED:-10.11}"
    local wanted="${MARIADB_REQUIRED:-10.11.0}"
    local series="$(printf '%s' "${wanted}" | awk -F. '{print $1"."$2}')"

    if curl -fsSL https://r.mariadb.com/downloads/mariadb_repo_setup -o /tmp/mariadb_repo_setup; then
        chmod +x /tmp/mariadb_repo_setup
        bash /tmp/mariadb_repo_setup --mariadb-server-version="mariadb-${series}" || warn "Failed to configure MariaDB ${series} repository; trying the distribution repository."
        pkg_update
    else
        warn "Could not download mariadb_repo_setup; trying the distribution repository."
    fi

    pkg_install MariaDB-server MariaDB-client || pkg_install mariadb-server mariadb

    DB_SERVICE="mariadb"
    systemctl enable --now mariadb || systemctl enable --now mysql
}

setup_mysql_yum_repository() {
    [[ "${OS_FAMILY}" == "rhel" || "${OS_FAMILY}" == "fedora" ]] || return 0

    local major="${OS_VERSION_ID%%.*}"
    local platform=""
    if [[ "${OS_FAMILY}" == "fedora" ]]; then
        platform="fc${major}"
    else
        platform="el${major}"
        ${PKG_MANAGER} -y module disable mysql >/dev/null 2>&1 || true
    fi

    log "Configuring the official MySQL Yum/DNF repository for MySQL ${MYSQL_REQUIRED:-8.4}"
    pkg_install "https://repo.mysql.com/mysql84-community-release-${platform}-1.noarch.rpm" || warn "Could not install the MySQL repository RPM for ${platform}; trying the distribution repository."
}

install_mysql() {
    log "Installing MySQL >= ${MYSQL_REQUIRED:-8.4}"

    setup_mysql_yum_repository
    pkg_install mysql-community-server mysql-community-client || pkg_install mysql-server mysql || pkg_install community-mysql-server community-mysql
    DB_SERVICE="mysqld"
    systemctl enable --now mysqld || systemctl enable --now mysql
}

mysql_client() {
    if command_exists mysql; then
        command -v mysql
    elif command_exists mariadb; then
        command -v mariadb
    else
        return 1
    fi
}

run_mysql_socket() {
    local client
    client="$(mysql_client)" || return 1
    "${client}" -uroot "$@"
}

run_mysql_password() {
    local client
    client="$(mysql_client)" || return 1
    MYSQL_PWD="${DB_ROOT_PASS}" "${client}" -uroot "$@"
}

configure_database_root() {
    log "Configuring the database root password"
    local pass_sql
    pass_sql="$(printf '%s' "${DB_ROOT_PASS}" | sed "s/\\\\/\\\\\\\\/g; s/'/''/g")"

    local sql="
ALTER USER 'root'@'localhost' IDENTIFIED BY '${pass_sql}';
DELETE FROM mysql.user WHERE User='';
DROP DATABASE IF EXISTS test;
DELETE FROM mysql.db WHERE Db='test' OR Db='test\\_%';
FLUSH PRIVILEGES;
"

    if run_mysql_socket -e "SELECT 1" >/dev/null 2>&1; then
        run_mysql_socket -e "${sql}" || warn "Could not apply full hardening through the socket connection."
    elif run_mysql_password -e "SELECT 1" >/dev/null 2>&1; then
        run_mysql_password -e "${sql}" || warn "Could not apply full hardening through the password connection."
    else
        local current=""
        local client
        client="$(mysql_client)" || die "MySQL/MariaDB client was not found."

        if [[ "${DB_ENGINE}" == "mysql" && -f /var/log/mysqld.log ]]; then
            current="$(grep -i 'temporary password' /var/log/mysqld.log 2>/dev/null | tail -n1 | awk '{print $NF}' || true)"
            if [[ -n "${current}" ]]; then
                if MYSQL_PWD="${current}" "${client}" --connect-expired-password -uroot -e "${sql}" >/dev/null 2>&1; then
                    return 0
                fi
            fi
        fi

        if [[ "${NONINTERACTIVE}" == "1" ]]; then
            die "Could not authenticate to the database as root to apply the password."
        fi
        [[ -r /dev/tty ]] || die "Could not authenticate to the database and there is no terminal to ask the current root password."
        printf 'Current database root password, if one already exists: ' > /dev/tty
        if ! IFS= read -r -s current < /dev/tty; then
            printf '\n' > /dev/tty
            die "Could not read the current database root password."
        fi
        printf '\n' > /dev/tty
        MYSQL_PWD="${current}" "${client}" --connect-expired-password -uroot -e "${sql}" || die "Failed to configure the database root password."
    fi
}

validate_database_version() {
    local client version required label raw_version
    client="$(mysql_client)" || die "MySQL/MariaDB client was not found."
    raw_version="$(${client} --version || true)"

    if [[ "${DB_ENGINE}" == "mariadb" ]]; then
        required="${MARIADB_REQUIRED:-10.11.0}"
        label="MariaDB"
        version="$(printf '%s' "${raw_version}" | grep -oE 'Distrib[[:space:]]+[0-9]+(\.[0-9]+){1,2}' | grep -oE '[0-9]+(\.[0-9]+){1,2}' | head -n1 || true)"
        if [[ -z "${version}" ]]; then
            version="$(printf '%s' "${raw_version}" | grep -oE '[0-9]+(\.[0-9]+){1,2}[^[:space:]]*-MariaDB' | grep -oE '^[0-9]+(\.[0-9]+){1,2}' | head -n1 || true)"
        fi
    else
        required="${MYSQL_REQUIRED:-8.4}"
        label="MySQL"
        version="$(printf '%s' "${raw_version}" | grep -oE '[0-9]+(\.[0-9]+){1,2}' | head -n1 || true)"
    fi

    [[ -n "${version}" ]] || die "Could not validate the database version. Raw output: ${raw_version}"
    if ! version_ge "${version}" "${required}"; then
        die "Installed ${label} (${version}) is lower than the Moodle requirement (${required}). Install a newer repository and run this installer again."
    fi
    log "${label} active: ${version}"
}

install_web_servers() {
    log "Installing Apache, NGINX and Certbot"
    pkg_install httpd nginx certbot python3-certbot-nginx || pkg_install httpd nginx certbot
}

install_bundled_nginx_files() {
    local source_dir="${INSTALL_DIR}/install/nginx"

    [[ -d "${source_dir}" ]] || return 0

    log "Installing bundled NGINX files into /etc/nginx"
    mkdir -p /etc/nginx/conf.d /etc/nginx/util /etc/nginx/cache

    if [[ -f "${source_dir}/conf.d/00-moodle-admin.conf" ]]; then
        install -D -m 0644 "${source_dir}/conf.d/00-moodle-admin.conf" /etc/nginx/conf.d/00-moodle-admin.conf
    else
        warn "Bundled NGINX file was not found: ${source_dir}/conf.d/00-moodle-admin.conf"
    fi

    if [[ -f "${source_dir}/util/cache.conf" ]]; then
        install -D -m 0644 "${source_dir}/util/cache.conf" /etc/nginx/util/cache.conf
    else
        warn "Bundled NGINX file was not found: ${source_dir}/util/cache.conf"
    fi
}

ensure_sites_enabled_includes() {
    mkdir -p /etc/httpd/sites-enabled /etc/nginx/sites-enabled

    install_bundled_nginx_files

    if [[ -f /etc/nginx/nginx.conf ]]; then
        sed -i -E '\|^[[:space:]]*include[[:space:]]+/etc/nginx/sites-enabled/\*;[[:space:]]*$|d' /etc/nginx/nginx.conf || true
    fi

    if ! grep -Rq "sites-enabled/\*.conf" /etc/httpd/conf /etc/httpd/conf.d 2>/dev/null; then
        printf '\nIncludeOptional sites-enabled/*.conf\n' >> /etc/httpd/conf/httpd.conf
    fi

    local nginx_include_file="/etc/nginx/conf.d/00-moodle-admin.conf"
    local nginx_include_line="include /etc/nginx/sites-enabled/*.conf;"

    touch "${nginx_include_file}"

    if ! grep -Eq '^[[:space:]]*include[[:space:]]+/etc/nginx/sites-enabled/[^;]*;' "${nginx_include_file}" 2>/dev/null; then
        printf '\n%s\n' "${nginx_include_line}" >> "${nginx_include_file}"
    fi
}

configure_apache_port() {
    log "Configuring Apache to listen only on 8080"
    sed -i -E 's/^[[:space:]]*Listen[[:space:]]+80$/# Listen 80 disabled by Moodle Friendly Installation installer/' /etc/httpd/conf/httpd.conf || true
    grep -q '^Listen 8080$' /etc/httpd/conf/httpd.conf || printf '\nListen 8080\n' >> /etc/httpd/conf/httpd.conf
    if command_exists semanage; then
        semanage port -a -t http_port_t -p tcp 8080 >/dev/null 2>&1 || semanage port -m -t http_port_t -p tcp 8080 >/dev/null 2>&1 || true
    fi
    setsebool -P httpd_can_network_connect 1 >/dev/null 2>&1 || true
}

configure_firewall() {
    if systemctl is-active --quiet firewalld; then
        firewall-cmd --permanent --add-service=http || true
        firewall-cmd --permanent --add-service=https || true
        firewall-cmd --reload || true
    fi
}

ensure_php_dependencies() {
    if [[ -f "${INSTALL_DIR}/public/app/vendor/autoload.php" ]]; then
        return 0
    fi

    if [[ ! -f "${INSTALL_DIR}/public/app/composer.json" ]]; then
        warn "PHP vendor was not found and composer.json does not exist either."
        return 0
    fi

    log "Installing panel PHP dependencies through Composer"
    if ! command_exists composer; then
        pkg_install composer || true
    fi

    command_exists composer || die "Composer is not installed and public/app/vendor/autoload.php does not exist. Install Composer or commit the vendor/ directory."
    (cd "${INSTALL_DIR}/public/app" && composer install --no-dev --optimize-autoloader --no-interaction) || die "composer install failed."
}

update_panel_config_values() {
    local config_file="$1"
    shift

    python3 - "${config_file}" "$@" <<'PY'
import re
import sys
from pathlib import Path

path = Path(sys.argv[1])
updates = []
for raw in sys.argv[2:]:
    key, value = raw.split('=', 1)
    updates.append((key, value))

text = path.read_text(errors='ignore')

for key, value in updates:
    pattern = re.compile(
        r"(?m)^(?P<prefix>[ \t]*['\"]" + re.escape(key) + r"['\"]\s*=>\s*)(?P<value>[^,\n]*)(?P<suffix>,\s*)$"
    )

    def repl(match):
        return f"{match.group('prefix')}{value}{match.group('suffix')}"

    text, count = pattern.subn(repl, text, count=1)
    if count:
        continue

    insert = f"    '{key}' => {value},\n"
    end_match = re.search(r"(?m)^\s*\];\s*$", text)
    if not end_match:
        raise SystemExit(f"Could not update {path}: closing array marker ]; was not found")
    text = text[:end_match.start()] + insert + text[end_match.start():]

path.write_text(text)
PY
}

create_panel_config() {
    log "Updating panel public/config.php"

    local config_file="${INSTALL_DIR}/public/config.php"
    if [[ ! -f "${config_file}" ]]; then
        if [[ -f "${INSTALL_DIR}/public/config-example.php" ]]; then
            cp "${INSTALL_DIR}/public/config-example.php" "${config_file}"
        else
            cat > "${config_file}" <<'PHP'
<?php

return [
    'reserved_domains' => [
        'admin.moodle',
    ],
];
PHP
        fi
    fi

    local app_name base_url mysql_pass phpbin apache_user apache_group
    app_name="$(safe_php_string "Moodle Friendly Installation")"
    base_url="$(safe_php_string "${BASE_URL}")"
    mysql_pass="$(safe_php_string "${DB_ROOT_PASS}")"
    phpbin="$(safe_php_string "${PHP_BIN}")"
    apache_user="$(safe_php_string "apache")"
    apache_group="$(safe_php_string "apache")"

    update_panel_config_values "${config_file}" \
        "app_name=${app_name}" \
        "base_url=${base_url}" \
        "base_dir=realpath(__DIR__ . '/..')" \
        "default_moodle_branch='${MOODLE_STABLE_BRANCH}'" \
        "db_engine='${DB_ENGINE}'" \
        "apache_user=${apache_user}" \
        "apache_group=${apache_group}" \
        "php_bin=${phpbin}" \
        "mysql_admin_host='localhost'" \
        "mysql_admin_port=3306" \
        "mysql_admin_socket=null" \
        "mysql_admin_user='root'" \
        "mysql_admin_pass=${mysql_pass}"
}
remove_legacy_panel_vhost() {
    local dir="$1"
    local file="$2"
    local target_file="${dir}/admin.moodle.conf"

    [[ -n "${file}" ]] || return 0
    [[ "${file}" != "${target_file}" ]] || return 0
    [[ -f "${file}" ]] || return 0

    if grep -Eq "DocumentRoot[[:space:]]+${INSTALL_DIR}/public|moodle-friendly-installation|proxy_pass[[:space:]]+http://127\\.0\\.0\\.1:8080" "${file}" 2>/dev/null; then
        rm -f "${file}"
    fi
}

cleanup_legacy_panel_vhosts() {
    local dir="$1"
    local current_file="${dir}/admin.moodle.conf"
    local legacy_file

    for legacy_file in "${dir}/${SERVER_NAME}.conf" "${dir}/_.conf"; do
        remove_legacy_panel_vhost "${dir}" "${legacy_file}"
    done

    if [[ -d "${dir}" ]]; then
        while IFS= read -r legacy_file; do
            [[ "${legacy_file}" != "${current_file}" ]] || continue
            remove_legacy_panel_vhost "${dir}" "${legacy_file}"
        done < <(grep -RlE "DocumentRoot[[:space:]]+${INSTALL_DIR}/public|moodle-friendly-installation|proxy_pass[[:space:]]+http://127\\.0\\.0\\.1:8080" "${dir}"/*.conf 2>/dev/null || true)
    fi
}

write_apache_vhost() {
    local file="/etc/httpd/sites-enabled/admin.moodle.conf"
    cleanup_legacy_panel_vhosts "/etc/httpd/sites-enabled"
    local server_for_apache="${PANEL_DOMAIN:-${PUBLIC_IP}}"
    local apache_log_dir="/var/log/httpd"
    cat > "${file}" <<APACHE
<VirtualHost *:8080>
    ServerName ${server_for_apache}
    DocumentRoot ${INSTALL_DIR}/public

    <Directory ${INSTALL_DIR}>
        Require all denied
    </Directory>

    <Directory ${INSTALL_DIR}/public>
        Options FollowSymLinks
        AllowOverride All
        Require all granted
    </Directory>

    <FilesMatch \.php$>
        SetHandler "proxy:unix:${PHP_FPM_SOCKET}|fcgi://localhost/"
    </FilesMatch>

    ErrorLog ${apache_log_dir}/moodle-friendly-installation-error.log
    CustomLog ${apache_log_dir}/moodle-friendly-installation-access.log combined
</VirtualHost>
APACHE
}

write_nginx_vhost() {
    local file="/etc/nginx/sites-enabled/admin.moodle.conf"
    cleanup_legacy_panel_vhosts "/etc/nginx/sites-enabled"
    local listen="listen 80;"
    local server_name="${PANEL_DOMAIN:-_}"
    if [[ -z "${PANEL_DOMAIN}" ]]; then
        listen="listen 80 default_server;"
    fi

    rm -f /etc/nginx/sites-enabled/default /etc/nginx/conf.d/default.conf 2>/dev/null || true

    cat > "${file}" <<NGINX
server {
    ${listen}
    server_name ${server_name};

    client_max_body_size 128m;

    location / {
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_set_header X-Forwarded-Host \$host;
        proxy_read_timeout 300;
        proxy_connect_timeout 300;
        proxy_pass http://127.0.0.1:8080;
    }
}
NGINX
}

set_permissions() {
    log "Adjusting permissions"
    chown -R root:apache "${INSTALL_DIR}"
    find "${INSTALL_DIR}" -type d -exec chmod 0750 {} \;
    find "${INSTALL_DIR}" -type f -exec chmod 0640 {} \;
    chmod +x "${INSTALL_DIR}/bin/cron-root-runner.php" "${INSTALL_DIR}/bin/cron-install_moodle.php" "${INSTALL_DIR}/bin/cron-app_build.php" 2>/dev/null || true
    chmod 0770 "${INSTALL_DIR}/data" "${INSTALL_DIR}/runtime" "${INSTALL_DIR}/logs" "${INSTALL_DIR}/queue"
    chmod 0770 "${INSTALL_DIR}/app-MoodleMobile-V2/res"
    chmod 0640 "${INSTALL_DIR}/public/config.php" "${INSTALL_DIR}/data/users.json"

    if command_exists restorecon; then
        if command_exists semanage; then
            semanage fcontext -a -t httpd_sys_content_t "${INSTALL_DIR}/public(/.*)?" >/dev/null 2>&1 || true
            semanage fcontext -a -t httpd_sys_rw_content_t "${INSTALL_DIR}/(data|runtime|logs|queue)(/.*)?" >/dev/null 2>&1 || true
        fi
        restorecon -R "${INSTALL_DIR}" >/dev/null 2>&1 || true
    fi
}

configure_cron() {
    log "Configuring the panel root cron"
    cat > /etc/cron.d/moodle-friendly-installation-runner <<CRON
* * * * * root ${PHP_BIN} ${INSTALL_DIR}/bin/cron-root-runner.php >>/var/log/moodle-friendly-installation-runner.log 2>&1
CRON
    chmod 0644 /etc/cron.d/moodle-friendly-installation-runner
}

restart_unit_with_retry() {
    local unit="$1"
    local attempt=1
    local max_attempts=3

    while (( attempt <= max_attempts )); do
        if systemctl restart "${unit}"; then
            return 0
        fi

        warn "Could not restart ${unit} on attempt ${attempt}/${max_attempts}. Retrying..."
        systemctl status "${unit}" --no-pager -l || true
        sleep 2
        attempt=$((attempt + 1))
    done

    journalctl -u "${unit}" -n 80 --no-pager || true
    die "Failed to restart ${unit}."
}

restart_services() {
    log "Validating and restarting services"

    systemctl enable "${PHP_FPM_SERVICE}"
    restart_unit_with_retry "${PHP_FPM_SERVICE}"

    httpd -t

    systemctl enable httpd
    restart_unit_with_retry httpd

    nginx -t

    # Do not use `systemctl enable --now nginx` here. On Fedora/RHEL,
    # `--now` can try to start NGINX before Apache has fully released port 80
    # after being moved to 127.0.0.1:8080, causing a false installer failure.
    systemctl enable nginx
    restart_unit_with_retry nginx
}

prompt_lets_encrypt_email() {
    local default_email="admin@${PANEL_DOMAIN}"
    local value=""

    if [[ "${NONINTERACTIVE}" == "1" ]]; then
        LE_EMAIL="${LE_EMAIL:-${default_email}}"
    elif ui_available; then
        value="$(whiptail \
            --title "Moodle Friendly Installation" \
            --inputbox "Digite o e-mail para registrar o certificado Let's Encrypt." \
            10 78 "${LE_EMAIL:-${default_email}}" \
            3>&1 1>&2 2>&3 < /dev/tty)" || die "Let's Encrypt email input cancelled."

        LE_EMAIL="${value:-${default_email}}"
    else
        prompt_text LE_EMAIL "E-mail para Let's Encrypt" "${LE_EMAIL:-${default_email}}"
    fi

    LE_EMAIL="$(printf '%s' "${LE_EMAIL}" | tr -d '[:space:]')"
}

issue_lets_encrypt() {
    [[ -n "${PANEL_DOMAIN}" ]] || return 0

    prompt_lets_encrypt_email
    [[ "${LE_EMAIL}" =~ ^[^@[:space:]]+@[^@[:space:]]+\.[^@[:space:]]+$ ]] || die "Invalid Let's Encrypt email."

    log "Issuing Let's Encrypt certificate for ${PANEL_DOMAIN}"
    certbot --nginx -d "${PANEL_DOMAIN}" --non-interactive --agree-tos -m "${LE_EMAIL}" --redirect || die "Failed to issue the Let's Encrypt certificate. Check DNS, ports 80/443 and firewall."
    systemctl reload nginx
}

terminal_link() {
    local url="$1"
    local label="${2:-$1}"

    # OSC 8 hyperlink. Supported by many modern terminals.
    printf '\033]8;;%s\033\\%s\033]8;;\033\\' "${url}" "${label}"
}

final_check() {
    local url="${BASE_URL}"
    local apache_service="apache2"
    local curl_ok="0"

    if systemctl list-unit-files httpd.service >/dev/null 2>&1; then
        apache_service="httpd"
    fi

    local reset="\033[0m"
    local bold="\033[1m"
    local green="\033[1;32m"
    local yellow="\033[1;33m"
    local blue="\033[1;34m"
    local cyan="\033[1;36m"
    local white="\033[1;37m"
    local navy="\033[1;34m"
    local blue="\033[0;34m"
    local cyan="\033[0;36m"
    local white="\033[1;37m"
    local green="\033[0;32m"

    local sep="------------------------------------------------------------"

    log "Final test: ${url}"

    if curl -k -fsSI --max-time 15 "${url}" >/dev/null 2>&1; then
        curl_ok="1"
        printf '\n%b==>%b Panel is responding at ' "${green}" "${reset}"
        terminal_link "${url}" "${url}"
        printf '\n'
    else
        warn "Could not validate through curl. Check: systemctl status nginx ${apache_service} ${PHP_FPM_SERVICE}"
    fi

    printf '\n'

    final_banner_line() {
        printf '%b------------------------------------------------------------%b\n' "${cyan}" "${reset}"
    }

    final_banner_points() {
        printf '%b. . . . . . . . . . . . . . . . . . . . . . . . . . . .%b\n' "${yellow}" "${reset}"
    }

    final_banner_animate() {
        local text="$1"
        local color="$2"
        local i

        for ((i = 0; i < ${#text}; i++)); do
            printf '%b%s%b' "${color}" "${text:${i}:1}" "${reset}"
            sleep 0.01
        done
        printf '\n'
    }

    final_banner_line
    final_banner_points
    printf '%b' "${bold}${navy}"
    final_banner_animate "███╗   ███╗ ██████╗  ██████╗ ██████╗ ██╗     ███████╗" "${navy}"
    final_banner_animate "████╗ ████║██╔═══██╗██╔═══██╗██╔══██╗██║     ██╔════╝" "${blue}"
    final_banner_animate "██╔████╔██║██║   ██║██║   ██║██║  ██║██║     █████╗  " "${cyan}"
    final_banner_animate "██║╚██╔╝██║██║   ██║██║   ██║██║  ██║██║     ██╔══╝  " "${green}"
    final_banner_animate "██║ ╚═╝ ██║╚██████╔╝╚██████╔╝██████╔╝███████╗███████╗" "${white}"
    final_banner_animate "╚═╝     ╚═╝ ╚═════╝  ╚═════╝ ╚═════╝ ╚══════╝╚══════╝" "${white}"
    printf '%b' "${reset}"

    final_banner_points
    final_banner_line

    if [[ "${curl_ok}" == "1" ]]; then
        sleep 0.5
        printf '%b        ... System started successfully. ...%b\n' "${green}" "${reset}"
        printf '\n'
        final_banner_line
    else
        printf '%b%s%b\n' "${yellow}" "Installation completed, but the final HTTP test needs attention." "${reset}"
    fi

    printf '\n'
    printf '%bAccess panel:%b ' "${bold}${white}" "${reset}"
    terminal_link "${url}" "${url}"
    printf '\n'

    printf '%b%s%b\n' "${cyan}" "${sep}" "${reset}"
    printf '%b%-14s%b %s\n' "${bold}" "Panel URL:" "${reset}" "${url}"
    printf '%b%-14s%b %s\n' "${bold}" "Directory:" "${reset}" "${INSTALL_DIR}"
    printf '%b%-14s%b %s\n' "${bold}" "Config:" "${reset}" "${INSTALL_DIR}/public/config.php"
    printf '%b%-14s%b %s\n' "${bold}" "Cron:" "${reset}" "/etc/cron.d/moodle-friendly-installation-runner"
    printf '%b%-14s%b %s\n' "${bold}" "Runner log:" "${reset}" "/var/log/moodle-friendly-installation-runner.log"
    printf '%b%-14s%b %s\n' "${bold}" "Services:" "${reset}" "nginx ${apache_service} ${PHP_FPM_SERVICE}"
    printf '%b%s%b\n' "${cyan}" "${sep}" "${reset}"

    if [[ "${curl_ok}" != "1" ]]; then
        printf '\n%bDiagnostic commands:%b\n' "${yellow}" "${reset}"
        printf '  systemctl status nginx %s %s\n' "${apache_service}" "${PHP_FPM_SERVICE}"
        printf '  journalctl -u nginx -n 80 --no-pager\n'
        printf '  journalctl -u %s -n 80 --no-pager\n' "${apache_service}"
        printf '  journalctl -u %s -n 80 --no-pager\n' "${PHP_FPM_SERVICE}"
        printf '%b%s%b\n' "${cyan}" "${sep}" "${reset}"
    fi

    printf '\n'
}


base_packages_installed() {
    local required_commands=(curl wget git unzip tar python3 sed grep awk openssl)
    local command_name

    for command_name in "${required_commands[@]}"; do
        command_exists "${command_name}" || return 1
    done

    command_exists systemctl || return 1

    return 0
}

php_extensions_ok() {
    local phpbin="$1"
    local modules=""
    local extension=""
    local missing=()

    modules="$(${phpbin} -m 2>/dev/null | tr '[:upper:]' '[:lower:]' || true)"
    [[ -n "${modules}" ]] || return 1

    for extension in curl dom mbstring zip gd intl soap opcache bcmath ldap mysqli pdo_mysql; do
        if [[ "${extension}" == "opcache" ]]; then
            if ! printf '%s\n' "${modules}" | grep -Eqx '(opcache|zend opcache)'; then
                missing+=("${extension}")
            fi
            continue
        fi

        if ! printf '%s\n' "${modules}" | grep -qx "${extension}"; then
            missing+=("${extension}")
        fi
    done

    if (( ${#missing[@]} > 0 )); then
        warn "PHP is installed, but missing required extensions: ${missing[*]}"
        return 1
    fi

    return 0
}

php_requirement_installed() {
    [[ -n "${PHP_REQUIRED:-}" ]] || return 1

    local candidates=()
    local candidate=""
    local phpbin=""
    local php_current=""

    [[ -n "${PHP_BIN:-}" ]] && candidates+=("${PHP_BIN}")
    [[ -n "${PHP_SERIES:-}" ]] && candidates+=("/usr/bin/php${PHP_SERIES}" "php${PHP_SERIES}")
    candidates+=(php)

    for candidate in "${candidates[@]}"; do
        if [[ "${candidate}" == /* ]]; then
            [[ -x "${candidate}" ]] || continue
            phpbin="${candidate}"
        else
            phpbin="$(command -v "${candidate}" 2>/dev/null || true)"
            [[ -n "${phpbin}" ]] || continue
        fi

        php_current="$(${phpbin} -r 'echo PHP_VERSION;' 2>/dev/null || true)"
        [[ -n "${php_current}" ]] || continue
        version_ge "${php_current}" "${PHP_REQUIRED}" || continue
        php_extensions_ok "${phpbin}" || return 1

        PHP_BIN="${phpbin}"
        PHP_SERIES="$(${PHP_BIN} -r 'echo PHP_MAJOR_VERSION.".".PHP_MINOR_VERSION;' 2>/dev/null || printf '%s' "${PHP_SERIES}")"
        PHP_FPM_SERVICE="php-fpm"
        PHP_FPM_SOCKET="/run/php-fpm/www.sock"

        if command_exists systemctl && ! systemctl list-unit-files "${PHP_FPM_SERVICE}.service" >/dev/null 2>&1; then
            warn "PHP CLI satisfies the requirement, but ${PHP_FPM_SERVICE} is not installed. PHP installation will run."
            return 1
        fi

        return 0
    done

    return 1
}

database_requirement_installed() {
    [[ -n "${DB_ENGINE:-}" ]] || return 1

    local client=""
    local raw_version=""
    local version=""
    local required=""
    local label=""

    client="$(mysql_client 2>/dev/null || true)"
    [[ -n "${client}" ]] || return 1
    raw_version="$(${client} --version 2>/dev/null || true)"
    [[ -n "${raw_version}" ]] || return 1

    if [[ "${DB_ENGINE}" == "mariadb" ]]; then
        required="${MARIADB_REQUIRED:-10.11.0}"
        label="MariaDB"
        printf '%s' "${raw_version}" | grep -qi 'mariadb' || return 1
        version="$(printf '%s' "${raw_version}" | grep -oE 'Distrib[[:space:]]+[0-9]+(\.[0-9]+){1,2}' | grep -oE '[0-9]+(\.[0-9]+){1,2}' | head -n1 || true)"
        if [[ -z "${version}" ]]; then
            version="$(printf '%s' "${raw_version}" | grep -oE '[0-9]+(\.[0-9]+){1,2}[^[:space:]]*-MariaDB' | grep -oE '^[0-9]+(\.[0-9]+){1,2}' | head -n1 || true)"
        fi
        if command_exists systemctl && systemctl list-unit-files mariadb.service >/dev/null 2>&1; then
            DB_SERVICE="mariadb"
        elif command_exists systemctl && systemctl list-unit-files mysql.service >/dev/null 2>&1; then
            DB_SERVICE="mysql"
        else
            DB_SERVICE="mariadb"
        fi
    else
        required="${MYSQL_REQUIRED:-8.4}"
        label="MySQL"
        printf '%s' "${raw_version}" | grep -qi 'mariadb' && return 1
        version="$(printf '%s' "${raw_version}" | grep -oE '[0-9]+(\.[0-9]+){1,2}' | head -n1 || true)"
        if command_exists systemctl && systemctl list-unit-files mysql.service >/dev/null 2>&1; then
            DB_SERVICE="mysql"
        elif command_exists systemctl && systemctl list-unit-files mysqld.service >/dev/null 2>&1; then
            DB_SERVICE="mysqld"
        else
            DB_SERVICE="mysql"
        fi
    fi

    [[ -n "${version}" ]] || return 1
    if ! version_ge "${version}" "${required}"; then
        warn "${label} is installed (${version}), but Moodle requires ${required}. Database installation will run."
        return 1
    fi

    return 0
}

web_servers_requirement_installed() {
    command_exists nginx || return 1
    command_exists certbot || return 1

    command_exists httpd || return 1

    return 0
}

lets_encrypt_certificate_exists() {
    [[ -n "${PANEL_DOMAIN:-}" ]] || return 1
    [[ -f "/etc/letsencrypt/live/${PANEL_DOMAIN}/fullchain.pem" ]] || return 1
    [[ -f "/etc/letsencrypt/live/${PANEL_DOMAIN}/privkey.pem" ]] || return 1
    return 0
}

load_existing_panel_config() {
    local config_file="${INSTALL_DIR}/public/config.php"
    local existing_pass=""

    [[ -f "${config_file}" ]] || return 0

    existing_pass="$(python3 - "${config_file}" <<'PY'
import re
import sys
from pathlib import Path

text = Path(sys.argv[1]).read_text(errors='ignore')
match = re.search(r"['\"]mysql_admin_pass['\"]\s*=>\s*('(?:\\.|[^'\\])*'|\"(?:\\.|[^\"\\])*\"|null)", text)
if not match:
    raise SystemExit(0)

token = match.group(1)
if token == 'null':
    raise SystemExit(0)

quote = token[0]
value = token[1:-1]

if quote == "'":
    value = value.replace("\\'", "'").replace('\\\\', '\\')
else:
    # This is intentionally conservative. Installer-generated values are single quoted,
    # but this also supports the most common double-quoted escaping used manually.
    value = bytes(value, 'utf-8').decode('unicode_escape')

if value:
    print(value)
PY
)"

    [[ -n "${existing_pass}" ]] || return 0

    if [[ -n "${REQUESTED_DB_ROOT_PASS:-}" ]]; then
        log "Using database root password provided through DB_ROOT_PASS. Existing panel config was not used."
        return 0
    fi

    if [[ "${DB_ROOT_PASS:-}" != "${existing_pass}" ]]; then
        DB_ROOT_PASS="${existing_pass}"
        log "Loaded database root password from existing panel config.php."
        save_progress
    fi
}

main() {
    need_root
    load_progress
    detect_os
    open_interactive_terminal
    configure_selinux_permissive

    if base_packages_installed; then
        log "Base packages already satisfy the installer requirements. Skipping package bootstrap."
        mark_progress_done STEP_BASE_PACKAGES
    else
        install_base_packages
        mark_progress_done STEP_BASE_PACKAGES
    fi

    load_existing_panel_config
    fetch_moodle_environment
    ask_install_options
    detect_public_ip
    check_dns_before_continue

    if php_requirement_installed; then
        log "PHP already satisfies Moodle requirements. Skipping PHP installation."
        tune_php_ini
        systemctl enable --now "${PHP_FPM_SERVICE}"
        systemctl restart "${PHP_FPM_SERVICE}"
        mark_progress_done STEP_PHP
    else
        install_php
        mark_progress_done STEP_PHP
    fi

    if database_requirement_installed; then
        log "${DB_ENGINE} already satisfies Moodle requirements. Skipping database installation."
        systemctl enable --now "${DB_SERVICE}" || true
        configure_database_root
        validate_database_version
        mark_progress_done STEP_DATABASE
    else
        install_database
        mark_progress_done STEP_DATABASE
    fi

    if web_servers_requirement_installed; then
        log "Apache, NGINX and Certbot are already installed. Skipping web server package installation."
        mark_progress_done STEP_WEB_SERVERS
    else
        install_web_servers
        mark_progress_done STEP_WEB_SERVERS
    fi

    ensure_sites_enabled_includes
    configure_apache_port
    configure_firewall

    install_bundled_nginx_files

    create_panel_config
    write_apache_vhost
    write_nginx_vhost
    set_permissions
    mark_progress_done STEP_CONFIG

    configure_cron
    mark_progress_done STEP_CRON

    restart_services

    if lets_encrypt_certificate_exists; then
        log "Let's Encrypt certificate already exists for ${PANEL_DOMAIN}. Skipping certificate issue."
        mark_progress_done STEP_LETS_ENCRYPT
    else
        issue_lets_encrypt
        mark_progress_done STEP_LETS_ENCRYPT
    fi

    final_check
    mark_progress_done STEP_COMPLETE
}

main "$@"
