server {
    server_name          {{DOMAIN}};

    gzip                 on;
    gzip_proxied         any;
    gzip_types           text/plain text/xml text/css application/x-javascript text/javascript;
    gzip_vary            on;
    gzip_disable         "MSIE [1-6]\.(?!.*SV1)";

    location ~* \.(jpg|jpeg|png|gif|ico|webp|svg)$ {
        include                 /etc/nginx/util/cache.conf;
        add_header              EduardoKraus            '0123';
    }

    location /theme/yui_combo.php {
        include                 /etc/nginx/util/cache.conf;
        add_header              EduardoKraus            '0009';
    }

    location /theme/jquery.php {
        include                 /etc/nginx/util/cache.conf;
        add_header              EduardoKraus            '0018';
    }

    location /theme/styles.php {
        include                 /etc/nginx/util/cache.conf;
        add_header              EduardoKraus            '0041';
    }

    location /theme/ {
        include                 /etc/nginx/util/cache.conf;
        add_header              EduardoKraus            '0063';
    }

    location /lib/javascript.php {
        include                 /etc/nginx/util/cache.conf;
        add_header              EduardoKraus            '0073';
    }
    location /lib/requirejs.php {
        include                 /etc/nginx/util/cache.conf;
        add_header              EduardoKraus            '0079';
    }

    location /lib/ajax/service-nologin.php {
        include                 /etc/nginx/util/cache.conf;
        add_header              EduardoKraus            '0083';
    }

    location /local/kopere_dashboard/assets {
        include                 /etc/nginx/util/cache.conf;
        add_header              EduardoKraus            '0096';
    }

    location /pluginfile.php/1/ {
        include                 /etc/nginx/util/cache.conf;
        add_header              EduardoKraus            '0106';
    }

    location / {
        proxy_set_header        Host                    $host;
        proxy_set_header        X-Real-IP               $remote_addr;
        proxy_set_header        X-Forwarded-For         $proxy_add_x_forwarded_for;
        proxy_set_header        X-Forwarded-Proto       https;
        proxy_set_header        X-Forwarded-Host        $host;

        proxy_hide_header       X-Powered-By;
        add_header              Nginx-Route             '0017';

        proxy_pass              http://127.0.0.1:8080;
    }

    listen               80;
}
